//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2023.
// SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionProperties) DeepCopyInto(out *ConnectionProperties) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionProperties.
func (in *ConnectionProperties) DeepCopy() *ConnectionProperties {
	if in == nil {
		return nil
	}
	out := new(ConnectionProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DremioRestServer) DeepCopyInto(out *DremioRestServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DremioRestServer.
func (in *DremioRestServer) DeepCopy() *DremioRestServer {
	if in == nil {
		return nil
	}
	out := new(DremioRestServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DremioRestServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DremioRestServerList) DeepCopyInto(out *DremioRestServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DremioRestServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DremioRestServerList.
func (in *DremioRestServerList) DeepCopy() *DremioRestServerList {
	if in == nil {
		return nil
	}
	out := new(DremioRestServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DremioRestServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DremioRestServerSpec) DeepCopyInto(out *DremioRestServerSpec) {
	*out = *in
	out.Connection = in.Connection
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DremioRestServerSpec.
func (in *DremioRestServerSpec) DeepCopy() *DremioRestServerSpec {
	if in == nil {
		return nil
	}
	out := new(DremioRestServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DremioRestServerStatus) DeepCopyInto(out *DremioRestServerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DremioRestServerStatus.
func (in *DremioRestServerStatus) DeepCopy() *DremioRestServerStatus {
	if in == nil {
		return nil
	}
	out := new(DremioRestServerStatus)
	in.DeepCopyInto(out)
	return out
}
